# Generated by Django 3.2.16 on 2023-06-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20230622_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
