# Generated by Django 3.2.16 on 2023-07-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_dbproveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbproveedor',
            name='productos',
        ),
        migrations.AddField(
            model_name='dbproveedor',
            name='categorias',
            field=models.ManyToManyField(related_name='proveedores', to='inventario.Categoria'),
        ),
    ]
