# Generated by Django 3.2.16 on 2023-07-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_auto_20230702_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbproveedor',
            name='categorias',
        ),
        migrations.AddField(
            model_name='dbproveedor',
            name='productos',
            field=models.ManyToManyField(related_name='proveedores', to='inventario.Producto'),
        ),
    ]
