# Generated by Django 3.2.16 on 2023-07-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_auto_20230703_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbproveedor',
            name='productos',
            field=models.ManyToManyField(related_name='proveedores', to='inventario.Categoria'),
        ),
    ]
