# Generated by Django 3.2.16 on 2023-07-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_auto_20230708_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='categoria',
            field=models.ManyToManyField(related_name='categoria', to='inventario.Categoria'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='proveedor',
            field=models.ManyToManyField(related_name='proveedor', to='inventario.dbProveedor'),
        ),
    ]
