# Generated by Django 3.2.16 on 2023-07-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_auto_20230708_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='producto',
            field=models.ManyToManyField(related_name='producto', to='inventario.Producto'),
        ),
    ]
