# Generated by Django 3.2.16 on 2023-07-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='producto',
            field=models.ManyToManyField(related_name='productos', to='inventario.Producto'),
        ),
    ]
