# Generated by Django 3.2.16 on 2023-07-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_remove_pago_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='referencia',
        ),
    ]
