# Generated by Django 3.2.16 on 2023-07-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_remove_pago_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='empleados',
            field=models.ManyToManyField(related_name='empleado', to='inventario.Empleado'),
        ),
    ]
