# Generated by Django 3.2.16 on 2023-07-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_productos_vendidos', models.PositiveIntegerField()),
                ('ventas_por_categoria', models.TextField()),
            ],
        ),
    ]
