# Generated by Django 3.2.16 on 2023-07-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_reporteventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteventas',
            name='total_productos_vendidos',
        ),
        migrations.RemoveField(
            model_name='reporteventas',
            name='total_ventas',
        ),
        migrations.RemoveField(
            model_name='reporteventas',
            name='ventas_por_categoria',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AddField(
            model_name='reporteventas',
            name='ventas',
            field=models.ManyToManyField(to='inventario.Venta'),
        ),
    ]
