# Generated by Django 3.2.16 on 2023-07-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_auto_20230714_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='ventas',
            field=models.ManyToManyField(to='inventario.Venta'),
        ),
    ]
