# Generated by Django 3.2.16 on 2023-07-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_pago_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='empleado',
            field=models.ManyToManyField(related_name='Empleado', to='inventario.Empleado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
