# Generated by Django 3.2.16 on 2023-07-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0040_auto_20230720_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='empleados',
            field=models.ManyToManyField(related_name='emple', to='inventario.Empleado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='producto',
            field=models.ManyToManyField(related_name='produc', to='inventario.Producto'),
        ),
        migrations.AddField(
            model_name='factura',
            name='ventas',
            field=models.ManyToManyField(to='inventario.Venta'),
        ),
    ]
