# Generated by Django 3.2.16 on 2023-07-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0044_alter_venta_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='producto',
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('paypal', 'PayPal'), ('cheque', 'Cheque'), ('pago_movil', 'Pago Móvil'), ('criptomonedas', 'Criptomonedas'), ('pago_contra_entrega', 'Pago contra Entrega'), ('pago_a_plazos', 'Pago a Plazos')], max_length=50, null=True),
        ),
    ]
