# Generated by Django 3.2.16 on 2023-07-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0045_auto_20230720_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='cliente',
            field=models.ManyToManyField(related_name='client', to='inventario.Cliente'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='empleado',
            field=models.ManyToManyField(related_name='emple', to='inventario.Empleado'),
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ManyToManyField(related_name='prod', to='inventario.Producto'),
        ),
    ]
