# Generated by Django 3.2.16 on 2023-07-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0048_ticketcompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcompra',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='ticketcompra',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='ticketcompra',
            name='total',
        ),
        migrations.AddField(
            model_name='ticketcompra',
            name='venta',
            field=models.ManyToManyField(related_name='ven', to='inventario.Venta'),
        ),
    ]
