# Generated by Django 3.2.16 on 2023-07-31 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0053_auto_20230724_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='precio_uni',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='subtotal',
            field=models.FloatField(default=0),
        ),

    ]
