# Generated by Django 3.2.16 on 2023-08-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0055_auto_20230801_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(max_length=50, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='forma_pago',
            field=models.ManyToManyField(related_name='f_pago', to='inventario.MetodoPago'),
        ),
    ]
